AirforcePass/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('airforcePassWeb.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

airforcePassWeb/urls.py
from django.urls import path

from . import views

app_name = "airforcePassWeb"

urlpatterns = [
    path("signin/", views.userSignIn, name="signIn"),
    path('', views.index, name='index'),
    path('signUp/', views.userSignUp, name='signUp'),
    path("logout", views.logout_view, name="logout")
]

airforcePassWeb/models.py
from django.contrib.auth.models import User
from django.db import models
from AirforcePass import settings

# Create your models here.
class userProperties(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userproperties', null=False, name='user')
    cpf = models.CharField(max_length=14, unique=True)
    saram = models.CharField(max_length=15)
    birthDate = models.DateField(blank=True, null=True)
    photo = models.ImageField(null=True, blank=True)


class dependent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nome = models.TextField(max_length=120)
    email = models.EmailField()
    birthDate = models.DateField(blank=True, null=True)
    cpf = models.CharField(max_length=14, unique=True)

airforcePassWeb/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import userProperties, dependent
from django import forms
from django.forms import ModelForm
from AirforcePass import settings
from django.forms.utils import ErrorList


class DangerTextClass(ErrorList):
    def __str__(self):
        return self.as_custom

    def as_custom(self):
        if not self: return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<div class="text-danger">%s</div>' % e for e in self])

class userForm(ModelForm):

    error_messages = {
        'password_mismatch': "As duas senhas devem coincidir",
        'username_exists' : "Usuário já existe"
    }
    error_class = DangerTextClass

    username = forms.CharField(label="Usuário", error_messages={}, help_text="", 
    widget=forms.TextInput(attrs={'class': 'form-control'}))

    first_name = forms.CharField(label="Nome", 
    widget=forms.TextInput(attrs={'class': 'form-control'}))

    last_name = forms.CharField(label="Sobrenome", 
    widget=forms.TextInput(attrs={'class': 'form-control'}))

    password1 = forms.CharField(label="Senha",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    password2 = forms.CharField(label="Confirmação da Senha",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    email = forms.EmailField( required=True,
     widget= forms.EmailInput(attrs={'class': 'form-control'}))


    class Meta:
        model = User
        fields = ("username","first_name",
        "last_name",
        "email")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2


    def clean_username(self):
        username = self.cleaned_data.get("username")

        try:
            User._default_manager.get(username=username)
            #if the user exists, then let's raise an error message

            raise forms.ValidationError( 
            self.error_messages['username_exists'],  #my error message

            code='username_exists',   #set the error message key

                )
        except User.DoesNotExist:
            return username # if user does not exist so we can continue the registration process


    def save(self, commit=True):
        user = super(userForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        

        if commit:
            user.save()
        return user
    
    

class userPropForm(forms.ModelForm):
    birthDate = forms.DateField(
        label = "Data de Aniversário",
         required=False,
         widget=forms.DateInput(attrs={'type':'date','class':'form-control'} , format = '%d/%m/%Y'))

    photo = forms.ImageField(
        label="Foto", 
        required=False, widget=forms.FileInput(attrs={'class':'form-control-file'}))

    cpf = forms.CharField(max_length=14 ,widget=forms.TextInput( attrs={'class':'form-control','data-mask':"000.000.000.00",}))

    saram = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = userProperties
        exclude = ['user']

    def save(self,user, commit=True):
        userprop = super(userPropForm, self).save(commit=False)
        userprop.cpf = (self.cleaned_data["cpf"])
        userprop.saram = self.cleaned_data['saram']
        userprop.birthdate = self.cleaned_data['birthDate']
        userprop.photo = self.cleaned_data['photo']
        userprop.user = user
        if commit:
            userprop.save()
        return userprop

airforcePassWeb/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, reverse,get_object_or_404
from django import forms
import logging
from .forms import userForm, userPropForm

logger = logging.getLogger('app_api') #from LOGGING.loggers in settings.py

 #index control to user logged page
def index(request):
        return HttpResponseRedirect(reverse('airforcePassWeb:signIn'))


def userSignIn(request):
    
    userform = userForm()
    propform = userPropForm()
    
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST["username"]
            password = request.POST["password"]

            user = authenticate(username=username, password=password)
            #if authentication was sucessful
            if user is not None:
                if user.is_active:
                    login(request, user)

                    return render(request, 'users/userSignIn.html', {
                    "message" : "logged",
                    'userform' : userform,
                    'propertyform' : propform,
                })
            else:
                
                return render(request, 'users/userSignIn.html', {
                    "message" : "blocked",
                    'userform' : userform,
                    'propertyform' : propform
                })

        return render(request, 'users/userSignIn.html', {
                    "message" : "login",
                    'userform' : userform,
                    'propertyform' : propform
                })
    else:

        return render(request, 'users/userSignIn.html', {
                    "message" : "logged",
                    'userform' : userform,
                    'propertyform' : propform,
                    'user' : request.user})
    

# def user_update(request):
#     if request.user.is_authenticated:
#         userform = userForm(request or None, instance = request.user)
#         userpropform = userPropForm(request or None, instance = request.user.userproperties)
#     else:
#         return render(request, 'users/userSignIn.html',{
#                 "userform" : userform,
#                 'propertyform' : userpropform,
#                 'message' : 'blocked'})
#     if request.method == 'POST':
#         if userform.is_valid() and userpropform.is_valid():
#             userform.save(commit=True)
#             newuser = get_object_or_404(User, username=userform.cleaned_data['username'])
#             # ↓ pass the user to form to make the relationship ↓
#             userpropform.save(newuser,commit=True)
#             return render(request, 'users/userSignIn.html', {
#                         "message" : "logged",
#                         'userform' : userform,
#                         'propertyform' : userpropform})
#         else:
#             # if the form is not valid return the page with modal opened 
#             return render(request, 'users/userSignIn.html',{
#                 "userform" : userform,
#                 'propertyform' : userpropform,
#                 'message' : 'blocked',
#                 # ↓ open the modal ↓
#                 'modalMessage' : True})




def logout_view(request):
    logout(request)
    return render(request, 'users/userSignIn.html', {
                        "message" : "login",
                        'userform' : userForm(),
                        'propertyform' : userPropForm()
                    })

# user register control
def userSignUp(request, currentmessage = ''):
    if request.method == 'POST':
        userform = userForm(request.POST)
        userprop = userPropForm(request.POST, request.FILES)

        # check form validation
        if userform.is_valid() and userprop.is_valid():
            
            userform.save(commit=True)
            newuser = get_object_or_404(User, username=userform.cleaned_data['username'])
            # ↓ pass the user to form to make the relationship ↓
            userprop.save(newuser,commit=True)

            # login the new user ↓
            if not request.user.is_authenticated:
                user1 = authenticate(username=userform.cleaned_data['username'], password=userform.cleaned_data['password1'])
                
                if user1:
                    if user1.is_active:
                        login(request, user1)
                        return render(request, 'users/userSignIn.html', {
                        "message" : "logged",
                        'userform' : userform,
                        'propertyform' : userprop
                    })
                else:
                    # return the page to the user with the modal opened
                    return render(request, 'users/userSignIn.html', {
                        # ↓ change the image ↓
                        "message" : "blocked",
                        'userform' : userform,
                        'propertyform' : userprop,
                        
                    })
            # if the user is logged return a default login page ( just for exception handling)
            return render(request, 'users/userSignIn.html', {
                "message" : "logged",
                'userform' : userform,
                'propertyform' : userprop
            })
        else:
            # if the form is not valid return the page with modal opened 
            return render(request, 'users/userSignIn.html',{
                "userform" : userform,
                'propertyform' : userprop,
                'message' : 'blocked',
                # ↓ open the modal ↓
                'modalMessage' : True})

airforcePassWeb/templates/shared/layout.html
<!DOCTYPE html>

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %} 
{% bootstrap_messages %} {# Display django.contrib.messages as Bootstrap alerts #}
{{ STATIC_URL }}

{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
     <script src="{% static 'js/scripts.js' %}"></script> 
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
    <title>AirForcePass</title>

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #111111">
        
        <a class="navbar-brand" style="color: #fcb414; text-shadow: 1px 1px 6px #e71837; " href="#">
            <img class="d-inline-block align-middle mr-2" src="{% static 'img/favicon.ico' %}"/>
            AirforceAccess
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto align-items-center">

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'airforcePassWeb:signIn' %}">Ínicio <span class="sr-only">(current)</span></a>
                </li>
                 {% if request.user.is_superuser %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                {% endif %} 
            </ul>
            <ul class="navbar-nav ml-auto">
                {% comment %} checks if user is authenticated for  showing controls from login and register {% endcomment %}
                
                {% if request.user.is_authenticated %}
                    {# shows user name #}
                    <li class="nav-item active " data-toggle="modal" data-target="#exampleModal">
                        <a type="button" class="nav-link">{{ request.user.username }} </a>
                    </li>
                    {% comment %} shows logout option {% endcomment %}
                    <li class="nav-item active ">
                        <a href="{% url 'airforcePassWeb:logout' %}" class="nav-link" type="button" >Sair</a>
                    </li>
                {% else %}
                    {% comment %} user register modal call button {% endcomment %}
                    <li class="nav-item active">
                        <a type="button" class="nav-link" data-toggle="modal" data-target="#exampleModal">Cadastrar <span class="sr-only">(current)</span></a>
                    </li>
                    {% comment %} user login dropdown menu {% endcomment %}
                    <li class="nav-item dropdown active dropleft">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                            Acesso
                        </a>
                        <div class="dropdown-menu" style="min-width:300px; width: auto; height: auto; padding: 10px;" aria-labelledby="navbarDropdown">
                            
                            {# formulario de login#}

                            <form class="form" action="{% url 'airforcePassWeb:signIn' %}" method="POST">
                                {% csrf_token %}

                                <div class="form-group">
                                  <label for="username-field">Usuário</label>
                                  <input type="text" class="form-control" id="username-field" name="username" >
                                  {% comment %} <small id="helpId" class="form-text text-muted">Help text</small> {% endcomment %}
                                </div>
                                <div class="form-group">
                                  <label for="password-field">Senha</label>
                                  <input  class="form-control" id="password-field" name="password" type="password">
                                  {% comment %} <small id="helpId" class="form-text text-muted">Help text</small> {% endcomment %}
                                </div>
                                <button class="btn btn-primary" type="submit">Login</button>
                            </form>

                            <div class="dropdown-divider"></div>
                            {% comment %}<a class="dropdown-item" href="#">Cadastrar</a>{% endcomment %}
                             <a class="dropdown-item" href="#">Esqueceu a Senha?</a> 
                        </div>
                    </li>

                {% endif %}
                
            </ul>

        </div>
    </nav>

{% block body %}
{% endblock %}
{% comment %} user register modal {% endcomment %}
<div class="modal fade in" id="exampleModal" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cadastro</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        
      </div>
      <div class="modal-body">
        {% comment %} User register Form {% endcomment %}
        {% if not request.user.is_authenticated %}
            <form action="{% url 'airforcePassWeb:signUp'  %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ userform.as_p }}
                {{ propertyform.as_p }}
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>  
            </form>
        {% endif %}
      </div>
      
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cadastro</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        
      </div>
      <div class="modal-body">
        {% comment %} User register Form {% endcomment %}
        {% if not request.user.is_authenticated %}
            <form action="{% url 'airforcePassWeb:signUp'  %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ userform.as_p }}
                {{ propertyform.as_p }}
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>  
            </form>
        {% endif %}
      </div>
      
    </div>
  </div>
</div>

{% if modalMessage %}
    <script type="text/javascript">
    $(window).on('load',function(){
        $('#exampleModal').modal('show');
    });
</script>
{% endif %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
</body>
</html>